title: Nick.pro re:coded
baseurl: http://code.nick.pro/
authorname: Nick Moline
authorlong: Nicholas Moline
authorshort: Nick
facebookurl: https://www.facebook.com/nickmoline
facebookid: 656268335
twittername: NickMoline
googleplus: https://plus.google.com/100038801356570551641/posts
linkedin: http://www.linkedin.com/in/nickmoline
github: https://github.com/nickmoline